import type { Metadata } from "next";
import { Nunito, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// seo
export const metadata: Metadata = {
  title: "Next-Pizza App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* высота приложения */}
        <main className="min-h-screen">
          {children}
          </main>
      </body>
    </html>
  );
}
